info:
  app:
    encodig: UTF-8
    java:
      source: 1.8
      target: 1.8
  name:
    of:
      app: Invoice Server Dev
management:
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/invoice
    username: root
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: DETECT
logging:
  level:
    root: info
  pattern:
    console: '%d %-5level %logger : %msg%n'